### ISSUE TITLE
[Notice] About the code used in your version checker.

### ISSUE THREAD

**Issue by ConorTheDev** [LucasCodesWeb/SnakeGame#1]
Hi, Lucas.

I have recently discovered that some of the code used in your Snake Game is used in some of ConorTheDev's projects. As this code is licensed under All Rights Reserved, you can't use it.

This isn't a DMCA takedown of your "game", it's a notice that we would like you to remove the code that was from ConorTheDev.

Regards,
Leah. (heh i'm conor's manager person now because i said so)

**Comment by ConorTheDev** [comment]
And yes, I do see that there *is* credits to Conor in the VersionChecker class, he would still like it removed.

**Comment by LucasGamer213** [comment]
Ok, I have rewritten VersionChecker. There is still some of your code but I hope you are fine with that.
